name: type_utils
version: 0.2.2

description: Utilities for managing type and base utility classes.

homepage: https://github.com/giorgiofran/type_utils
repository: https://github.com/giorgiofran/type_utils
funding:
  - https://www.paypal.com/donate?hosted_button_id=YRUNF9YWKX2NW

environment:
  sdk: '>=3.5.0 <4.0.0'

#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
